- ballcat-dependencies/pom.xml
- ballcat-extends/mybatis-plus-extend/pom.xml
- ballcat-extends/mybatis-plus-extend/src/main/java/com/hccake/extend/mybatis/plus/MybatisAutoConfiguration.java
- ballcat-extends/mybatis-plus-extend/src/main/java/com/hccake/extend/mybatis/plus/SqlInjector.java
- ballcat-extends/mybatis-plus-extend/src/main/java/com/hccake/extend/mybatis/plus/config/MybatisConfigurer.java
- ballcat-extends/mybatis-plus-extend/src/main/java/com/hccake/extend/mybatis/plus/config/MybatisProperties.java
- ballcat-extends/mybatis-plus-extend/src/main/java/com/hccake/extend/mybatis/plus/config/StaticConfig.java
- ballcat-extends/mybatis-plus-extend/src/main/java/com/hccake/extend/mybatis/plus/exception/MybatisMethodInstanceException.java
- ballcat-extends/mybatis-plus-extend/src/main/resources/META-INF/spring.factories
- ballcat-extends/mybatis-plus-mysql-extend/pom.xml
- ballcat-extends/mybatis-plus-mysql-extend/src/main/java/com/hccake/extend/mybatis/plus/mysql/BaseMapper.java
- ballcat-extends/mybatis-plus-mysql-extend/src/main/java/com/hccake/extend/mybatis/plus/mysql/Columns.java
- ballcat-extends/mybatis-plus-mysql-extend/src/main/java/com/hccake/extend/mybatis/plus/mysql/ExtendBaseMapper.java
- ballcat-extends/mybatis-plus-mysql-extend/src/main/java/com/hccake/extend/mybatis/plus/mysql/MybatisConfig.java
- ballcat-extends/mybatis-plus-mysql-extend/src/main/java/com/hccake/extend/mybatis/plus/mysql/methods/BaseInsertBatch.java
- ballcat-extends/mybatis-plus-mysql-extend/src/main/java/com/hccake/extend/mybatis/plus/mysql/methods/InsertIgnoreByBatch.java
- ballcat-extends/mybatis-plus-mysql-extend/src/main/java/com/hccake/extend/mybatis/plus/mysql/methods/InsertOrUpdateByBatch.java
- ballcat-extends/mybatis-plus-mysql-extend/src/main/java/com/hccake/extend/mybatis/plus/mysql/methods/InsertOrUpdateFieldByBatch.java
- ballcat-extends/pom.xml
- pom.xml
编写可配置的 mybatis-plus 扩展
扩展了几个 适用与 MySQL的 全局 insert 方法
> 扩展 mybatis-plus

- ballcat-common/ballcat-common-conf/src/main/java/com/hccake/ballcat/common/conf/exception/ExceptionHandleAutoConfiguration.java
- ballcat-dependencies/pom.xml
- ballcat-extends/ballcat-extend-dingtalk/pom.xml
- ballcat-extends/ballcat-extend-kafka-stream/pom.xml
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/KafkaStreamBuilder.java
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/core/AbstractKafka.java
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/core/AbstractProcessor.java
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/core/AbstractPunctuator.java
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/extend/AbstractKeyValueStorePunctuator.java
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/extend/AbstractStringStringStorePunctuator.java
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/store/KafkaKeyValueStore.java
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/store/KafkaWindow.java
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/util/ProcessorContextUtil.java
- ballcat-extends/ballcat-extend-kafka/pom.xml
- ballcat-extends/ballcat-extend-kafka/src/main/java/com/hccake/extend/kafka/KafkaConstants.java
- ballcat-extends/ballcat-extend-kafka/src/main/java/com/hccake/extend/kafka/KafkaConsumerBuilder.java
- ballcat-extends/ballcat-extend-kafka/src/main/java/com/hccake/extend/kafka/KafkaExtendProducer.java
- ballcat-extends/ballcat-extend-kafka/src/main/java/com/hccake/extend/kafka/KafkaProducerBuilder.java
- ballcat-extends/ballcat-extend-kafka/src/test/java/com/hccake/extend/KafkaTest.java
- ballcat-extends/pom.xml
- pom.xml
添加kafka扩展
添加kafka流处理扩展
修复邮件通知异常无法使用bug
> :bug: :sparkles:  添加kafka扩展，修复邮件通知bug

- ballcat-dependencies/pom.xml
> :bug: idea 没有把所有修改提交上去，这是丢失的

- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/config/AdminRuleConfig.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/controller/SysRoleController.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/controller/SysUserController.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/mapper/SysRoleMapper.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/mapper/SysUserMapper.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/model/entity/SysRole.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/service/SysAdminConfigService.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/service/SysRoleService.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/service/SysUserService.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/service/impl/SysAdminConfigServiceImpl.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/service/impl/SysRoleServiceImpl.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/service/impl/SysUserServiceImpl.java
- ballcat-admin/ballcat-admin-core/src/main/resources/META-INF/spring.factories
> :sparkles: 添加新功能

- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/lov/enums/HttpMethod.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/lov/enums/HttpParamsPosition.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/lov/enums/Tag.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/lov/model/entity/Lov.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/lov/model/entity/LovBody.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/lov/model/entity/LovSearch.java
- ballcat-common/ballcat-common-conf/src/main/java/com/hccake/ballcat/common/conf/exception/GlobalExceptionHandlerResolver.java
- ballcat-common/ballcat-common-core/src/main/java/com/hccake/ballcat/common/core/thread/AbstractQueueThread.java
- ballcat-dependencies/pom.xml
- ballcat-extends/ballcat-extend-kafka-stream/src/main/java/com/hccake/extend/kafka/stream/KafkaStreamBuilder.java
- ballcat-extends/ballcat-extend-kafka/src/main/java/com/hccake/extend/kafka/KafkaProducerBuilder.java
- ballcat-starters/ballcat-spring-boot-starter-kafka/pom.xml
- ballcat-starters/ballcat-spring-boot-starter-kafka/src/main/java/com/hccake/starter/kafka/KafkaAutoConfiguration.java
- ballcat-starters/ballcat-spring-boot-starter-kafka/src/main/java/com/hccake/starter/kafka/KafkaProperties.java
- ballcat-starters/ballcat-spring-boot-starter-kafka/src/main/resources/META-INF/spring.factories
- ballcat-starters/pom.xml
添加 MethodArgumentTypeMismatchException 类型异常捕获处理
新增 kafka-starter 模块
修改 DEFAULT_BATCH_TIMEOUT 默认值
> 添加 starter-kafka 模块

- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/model/entity/SysDictItem.java
- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/modules/sys/model/vo/DictItemVO.java
> 修改字典项附加属性值类型

- ballcat-starters/ballcat-spring-boot-starter-oss/src/main/java/com/hccake/ballcat/commom/oss/ClientBuilder.java
- ballcat-starters/ballcat-spring-boot-starter-oss/src/main/java/com/hccake/ballcat/commom/oss/OssAutoConfiguration.java
- ballcat-starters/ballcat-spring-boot-starter-oss/src/main/java/com/hccake/ballcat/commom/oss/OssClient.java
- ballcat-starters/ballcat-spring-boot-starter-oss/src/main/java/com/hccake/ballcat/commom/oss/OssProperties.java
- ballcat-starters/ballcat-spring-boot-starter-oss/src/main/java/com/hccake/ballcat/commom/oss/interceptor/ModifyPathInterceptor.java
(cherry picked from commit bbc0b8ddb5771f6980b5dba43609feb9e0e3b8c0)
> :recycle: 重构 OssClient 生成方式

- doc/3ballcat-i18n-0.5.0.sql
> :bug: 增加表的字符集

- ballcat-notify/ballcat-notify-biz/src/main/java/com/hccake/ballcat/notify/mapper/AnnouncementMapper.java
添加AnnouncementMapper.java的selectByPage方法
> 公告条件查询SQL语句错误

- ballcat-common/ballcat-common-log/src/main/java/com/hccake/ballcat/common/log/access/filter/AccessLogFilter.java
> 修复:抛BusinessException异常访问日志记录丢失traceId的问题

- ballcat-common/ballcat-common-log/src/main/java/com/hccake/ballcat/common/log/access/filter/AccessLogFilter.java
获取Servlet-mapping映射内的路径进行AntPathMatcher匹配
> 🎨 AntPathMatcher匹配Servlet-mapping映射内的路径

- ballcat-common/ballcat-common-i18n/src/main/java/com/hccake/ballcat/common/i18n/I18nField.java
- ballcat-common/ballcat-common-i18n/src/main/java/com/hccake/ballcat/common/i18n/I18nResponseAdvice.java
update I18nField.java add codeProperty usable range
> update I18nField.java add codeProperty usable range

- ballcat-common/ballcat-common-i18n/src/main/java/com/hccake/ballcat/common/i18n/I18nField.java
- ballcat-common/ballcat-common-i18n/src/main/java/com/hccake/ballcat/common/i18n/I18nResponseAdvice.java
- ballcat-common/ballcat-common-i18n/src/main/java/com/hccake/ballcat/common/i18n/I18nSupport.java
> fix bug add defaultMessage

- ballcat-system/ballcat-system-biz/src/main/java/com/hccake/ballcat/system/service/impl/SysUserServiceImpl.java
> :art: PasswordEncoder 优化

- ballcat-common/ballcat-common-core/src/main/java/com/hccake/ballcat/common/core/validation/constraints/EnumClass.java
- ballcat-common/ballcat-common-core/src/main/java/com/hccake/ballcat/common/core/validation/constraints/EnumValue.java
- ballcat-common/ballcat-common-core/src/main/java/com/hccake/ballcat/common/core/validation/validator/EnumClassValidator.java
- ballcat-common/ballcat-common-core/src/main/java/com/hccake/ballcat/common/core/validation/validator/EnumValueValidator.java
> :sparkles: Add custom validator

- ballcat-dependencies/pom.xml
- ballcat-starters/ballcat-spring-boot-starter-ip2region/pom.xml
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/config/Ip2regionAutoConfiguration.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/config/Ip2regionProperties.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/core/CacheType.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/core/IpInfo.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/searcher/CacheVectorIndexIp2regionSearcher.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/searcher/CacheXdbFileIp2regionSearcher.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/searcher/DirectIp2regionSearcher.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/searcher/Ip2regionSearcher.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/searcher/Ip2regionSearcherTemplate.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/java/com/hccake/ballcat/starter/ip2region/util/IpInfoUtils.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/resources/META-INF/spring.factories
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/test/java/com/hccake/ballcat/starter/ip2region/searcher/IndexCacheIp2regionSearcherTestTemplate.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/test/java/com/hccake/ballcat/starter/ip2region/searcher/Ip2regionSearcherTestTemplate.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/test/java/com/hccake/ballcat/starter/ip2region/searcher/NoneCacheIp2regionSearcherTestTemplate.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/test/java/com/hccake/ballcat/starter/ip2region/searcher/XdbCacheIp2regionSearcherTestTemplate.java
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/test/resources/application-index.yml
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/test/resources/application-xdb.yml
- ballcat-starters/ballcat-spring-boot-starter-ip2region/src/test/resources/application.yml
- ballcat-starters/pom.xml
> :sparkles: Introducing new features.封装Ip2region快速启动器

- ballcat-common/ballcat-common-idempotent/src/main/java/com/hccake/ballcat/common/idempotent/IdempotentAspect.java
- ballcat-starters/ballcat-spring-boot-starter-idempotent/pom.xml
- ballcat-starters/ballcat-spring-boot-starter-idempotent/src/main/java/com/hccake/ballcat/autoconfigure/idempotent/IdempotentAutoConfiguration.java
:heavy_minus_sign: Removing a dependency.移除一个测试用的无用包,避免包污染，使用redis作为幂等key存储能力时，redis的依赖由开发者自行解决
> 移除一个测试用的无用包,避免包污染

- ballcat-admin/ballcat-admin-core/src/main/java/com/hccake/ballcat/admin/upms/config/task/MdcTaskDecorator.java
Reverts ballcat-projects/ballcat#230
> Revert ":bug: 修复 MdcTaskDecorator 清除子线程MDC上下文时机不对 感谢 @Lotiner 的反馈"

- ballcat-common/ballcat-common-util/src/test/java/com/hccake/ballcat/common/util/TreeUtilsTest.java
- ballcat-system/ballcat-system-model/src/main/java/com/hccake/ballcat/system/model/dto/SysMenuCreateDTO.java
- ballcat-system/ballcat-system-model/src/main/java/com/hccake/ballcat/system/model/dto/SysMenuUpdateDTO.java
- ballcat-system/ballcat-system-model/src/main/java/com/hccake/ballcat/system/model/dto/SysUserDTO.java
- ballcat-system/ballcat-system-model/src/main/java/com/hccake/ballcat/system/model/qo/RoleBindUserQO.java
- ballcat-system/ballcat-system-model/src/main/java/com/hccake/ballcat/system/model/vo/SysUserPageVO.java
> :bug: 主键修改为 Long 类型的部分遗漏代码提交

- ballcat-starters/ballcat-spring-boot-starter-oss/src/main/java/com/hccake/ballcat/common/oss/DefaultOssTemplate.java
- ballcat-starters/ballcat-spring-boot-starter-oss/src/main/java/com/hccake/ballcat/common/oss/ObjectWithGlobalKeyPrefixOssTemplate.java
- ballcat-starters/ballcat-spring-boot-starter-oss/src/main/java/com/hccake/ballcat/common/oss/OssTemplate.java
- 支持对多个对象删除
- 支持(跨bucket)复制对象
- 支持获取文件预签名外链(前端上传或外围系统写入)
> :sparkles: 支持对多个对象删除，支持(跨bucket)复制对象，支持获取文件预签名外链(前端上传或外围系统写入)

- common/ballcat-common-core/pom.xml
- common/ballcat-common-core/src/main/java/org/ballcat/common/core/strategy/StrategyBeanProcessor.java
- common/ballcat-common-core/src/main/java/org/ballcat/common/core/strategy/StrategyComponent.java
- common/ballcat-common-core/src/main/java/org/ballcat/common/core/strategy/StrategyFactory.java
- common/ballcat-common-core/src/main/java/org/ballcat/common/core/strategy/StrategyInterface.java
- common/ballcat-common-core/src/test/java/org/ballcat/common/core/strategy/AppleFruit.java
- common/ballcat-common-core/src/test/java/org/ballcat/common/core/strategy/Fruit.java
- common/ballcat-common-core/src/test/java/org/ballcat/common/core/strategy/FruitType.java
- common/ballcat-common-core/src/test/java/org/ballcat/common/core/strategy/OrangeFruit.java
- common/ballcat-common-core/src/test/java/org/ballcat/common/core/strategy/StrategyTest.java
Now, you can use `@StrategyInterface` and `@StrategyComponent` to implement the Strategy Pattern. Then, use the `StrategyFactory` to  get the strategy instance
> :sparkles:Can use annotations to implement the Strategy Pattern

- ballcat-parent/src/checkstyle/checkstyle-suppressions.xml
- job/ballcat-spring-boot-starter-quartz/pom.xml
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/QuartzJobAutoConfiguration.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/constants/JobConstant.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/enums/JobExecuteTraceType.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/enums/JobStage.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/event/JobExecuteTraceEvent.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/event/listener/JobExecuteTraceStoreListener.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/job/CleanExecuteTraceJob.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/plugin/StoreJobHistoryPlugin.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/properties/QuartzJobProperties.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/service/QuartzJobService.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/service/impl/QuartzJobServiceImpl.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/store/JobExecuteTrace.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/store/JobExecuteTraceStore.java
- job/ballcat-spring-boot-starter-quartz/src/main/java/org/ballcat/autoconfigure/quartz/store/impl/JdbcJobExecuteTraceStore.java
- job/ballcat-spring-boot-starter-quartz/src/main/resources/META-INF/spring.factories
- job/ballcat-spring-boot-starter-quartz/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- job/ballcat-spring-boot-starter-quartz/src/test/java/org/ballcat/autoconfigure/quartz/JobStartupRunner.java
- job/ballcat-spring-boot-starter-quartz/src/test/java/org/ballcat/autoconfigure/quartz/TestApplication.java
- job/ballcat-spring-boot-starter-quartz/src/test/java/org/ballcat/autoconfigure/quartz/job/DemoJob.java
- job/ballcat-spring-boot-starter-quartz/src/test/resources/application-quartz.yml
- job/ballcat-spring-boot-starter-quartz/src/test/resources/application.yml
- pom.xml
1. 支持初始化Cron表达式任务、间隔任务、一次性任务
2. 支持运行时编程式修改、删除任务
3. 支持运行时编程式添加Cron表达式任务、间隔任务、一次性任务
> :sparkles: 增加Quartz定时任务starter
